/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
/**
 *
 * @author omarf
 */
public class CalculadoraLosaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraLosa
     */
    public CalculadoraLosaGUI() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngresarDMuro = new javax.swing.JPanel();
        txtAnchoLosa = new javax.swing.JTextField();
        lblLargoLosa = new javax.swing.JLabel();
        lblAnchoLosa = new javax.swing.JLabel();
        txtLargoLosa = new javax.swing.JTextField();
        lblMuro = new javax.swing.JLabel();
        lblEspesorLosa = new javax.swing.JLabel();
        txtEspesorLosa = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        pnlSpcMuro = new javax.swing.JPanel();
        lblSpcLosa = new javax.swing.JLabel();
        lblAreaLosa = new javax.swing.JLabel();
        txtAreaLosa = new javax.swing.JTextField();
        lblVolumenLosa = new javax.swing.JLabel();
        txtVolumenLosa = new javax.swing.JTextField();
        pnlMaterialesMuro = new javax.swing.JPanel();
        lblMaterialesLosa = new javax.swing.JLabel();
        lblCementoLosa = new javax.swing.JLabel();
        txtGravaLosa = new javax.swing.JTextField();
        lblConcretoLosa = new javax.swing.JLabel();
        txtConcretoLosa = new javax.swing.JTextField();
        txtVarillaLosa = new javax.swing.JTextField();
        lblVarillaLosa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnResetearMuro = new javax.swing.JButton();
        lblArenaLosa = new javax.swing.JLabel();
        lblGravaLosa = new javax.swing.JLabel();
        txtArenaLosa = new javax.swing.JTextField();
        txtCementoLosa = new javax.swing.JTextField();
        iconConcreto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Calculadora de losa");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIngresarDMuro.setBackground(new java.awt.Color(75, 75, 75));
        pnlIngresarDMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnchoLosa.setBackground(java.awt.Color.black);
        txtAnchoLosa.setForeground(java.awt.Color.white);
        pnlIngresarDMuro.add(txtAnchoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 121, -1));

        lblLargoLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoLosa.setForeground(java.awt.Color.white);
        lblLargoLosa.setText("Largo de la losa (m):");
        pnlIngresarDMuro.add(lblLargoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblAnchoLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAnchoLosa.setForeground(java.awt.Color.white);
        lblAnchoLosa.setText("Ancho de la losa (m):");
        pnlIngresarDMuro.add(lblAnchoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtLargoLosa.setBackground(java.awt.Color.black);
        txtLargoLosa.setForeground(java.awt.Color.white);
        txtLargoLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLargoLosaActionPerformed(evt);
            }
        });
        pnlIngresarDMuro.add(txtLargoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 121, -1));

        lblMuro.setBackground(java.awt.Color.white);
        lblMuro.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMuro.setForeground(java.awt.Color.white);
        lblMuro.setText("Calcular la cantidad de materiales para una losa");
        pnlIngresarDMuro.add(lblMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 50));

        lblEspesorLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblEspesorLosa.setForeground(java.awt.Color.white);
        lblEspesorLosa.setText("Espesor de la losa (m):");
        pnlIngresarDMuro.add(lblEspesorLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtEspesorLosa.setBackground(java.awt.Color.black);
        txtEspesorLosa.setForeground(java.awt.Color.white);
        pnlIngresarDMuro.add(txtEspesorLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 121, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.setFocusable(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlIngresarDMuro.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, 37));

        getContentPane().add(pnlIngresarDMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 230));

        pnlSpcMuro.setBackground(new java.awt.Color(36, 36, 36));
        pnlSpcMuro.setPreferredSize(new java.awt.Dimension(300, 255));
        pnlSpcMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpcLosa.setBackground(java.awt.Color.white);
        lblSpcLosa.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblSpcLosa.setForeground(java.awt.Color.white);
        lblSpcLosa.setText("Específicaciones de la losa");
        pnlSpcMuro.add(lblSpcLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 220, 50));

        lblAreaLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAreaLosa.setForeground(java.awt.Color.white);
        lblAreaLosa.setText("Área:");
        pnlSpcMuro.add(lblAreaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 67, -1, -1));

        txtAreaLosa.setEditable(false);
        txtAreaLosa.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaLosa.setForeground(java.awt.Color.white);
        txtAreaLosa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaLosaActionPerformed(evt);
            }
        });
        pnlSpcMuro.add(txtAreaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 93, 121, -1));

        lblVolumenLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVolumenLosa.setForeground(java.awt.Color.white);
        lblVolumenLosa.setText("Volumen:");
        pnlSpcMuro.add(lblVolumenLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 131, -1, -1));

        txtVolumenLosa.setEditable(false);
        txtVolumenLosa.setBackground(new java.awt.Color(0, 0, 0));
        txtVolumenLosa.setForeground(java.awt.Color.white);
        txtVolumenLosa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVolumenLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumenLosaActionPerformed(evt);
            }
        });
        pnlSpcMuro.add(txtVolumenLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 157, 121, -1));

        getContentPane().add(pnlSpcMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 310, 230));

        pnlMaterialesMuro.setBackground(new java.awt.Color(204, 204, 204));
        pnlMaterialesMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaterialesLosa.setBackground(java.awt.Color.white);
        lblMaterialesLosa.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMaterialesLosa.setText("Cantidad de materiales necesarios para levantar la losa");
        pnlMaterialesMuro.add(lblMaterialesLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 470, 64));

        lblCementoLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblCementoLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblCementoLosa.setText("Cemento:");
        pnlMaterialesMuro.add(lblCementoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtGravaLosa.setBackground(java.awt.Color.black);
        txtGravaLosa.setForeground(java.awt.Color.white);
        txtGravaLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGravaLosaActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtGravaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        lblConcretoLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblConcretoLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblConcretoLosa.setText("Concreto:");
        pnlMaterialesMuro.add(lblConcretoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtConcretoLosa.setBackground(java.awt.Color.black);
        txtConcretoLosa.setForeground(java.awt.Color.white);
        txtConcretoLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcretoLosaActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtConcretoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        txtVarillaLosa.setBackground(java.awt.Color.black);
        txtVarillaLosa.setForeground(java.awt.Color.white);
        txtVarillaLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarillaLosaActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtVarillaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        lblVarillaLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblVarillaLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVarillaLosa.setText("Varilla:");
        pnlMaterialesMuro.add(lblVarillaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arena.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemento.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 40));

        btnResetearMuro.setBackground(new java.awt.Color(255, 86, 86));
        btnResetearMuro.setText("RESETEAR");
        btnResetearMuro.setFocusable(false);
        btnResetearMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearMuroActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(btnResetearMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 40));

        lblArenaLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblArenaLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblArenaLosa.setText("Arena:");
        pnlMaterialesMuro.add(lblArenaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblGravaLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblGravaLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblGravaLosa.setText("Grava:");
        pnlMaterialesMuro.add(lblGravaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtArenaLosa.setBackground(java.awt.Color.black);
        txtArenaLosa.setForeground(java.awt.Color.white);
        txtArenaLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArenaLosaActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtArenaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        txtCementoLosa.setBackground(java.awt.Color.black);
        txtCementoLosa.setForeground(java.awt.Color.white);
        txtCementoLosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCementoLosaActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtCementoLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));

        iconConcreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Concreto.png"))); // NOI18N
        pnlMaterialesMuro.add(iconConcreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Varilla.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grava.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Losa.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, -1, -1));

        getContentPane().add(pnlMaterialesMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 720, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLargoLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLargoLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLargoLosaActionPerformed

    /**
     * Btn calcular, te calcula las especificaciones y materiales necesarios
     * para la losa
     *
     * @param evt
     */
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        // Calculamos el area
        CalculadoraMateriales l = new CalculadoraMateriales();
        double area = l.calcularArea(Double.parseDouble(txtAnchoLosa.getText()), Double.parseDouble(txtLargoLosa.getText()));
        txtAreaLosa.setText(area + " m2");

        // Calculamos el volumen
        double volumen = l.calcularVolumen(Double.parseDouble(txtAreaLosa.getText().replace(" m2", "").trim()), Double.parseDouble(txtEspesorLosa.getText()));
        txtVolumenLosa.setText(volumen + " m3");

        // Calcular materiales
        // Calculo de concreto, es directamente igual al volumen
        txtConcretoLosa.setText(txtVolumenLosa.getText());

        // Calculo de varilla
        double varilla = l.calcularVarilla(Double.parseDouble(txtAreaLosa.getText().replace(" m2", "").trim()));
        txtVarillaLosa.setText(varilla + " kg");

        DecimalFormat df = new DecimalFormat("#.00");

        // Calculo del cemento
        double cemento = l.calcularCementoLosa(Double.parseDouble(txtVolumenLosa.getText().replace(" m3", "").trim()));
        txtCementoLosa.setText(df.format(cemento) + " sacos");

        // Calculo de arena
        double arena = l.calcularArena(Double.parseDouble(txtVolumenLosa.getText().replace(" m3", "").trim()));
        txtArenaLosa.setText(df.format(arena) + " m3");

        // Calculo de grava, mismo que arena
        txtGravaLosa.setText(df.format(arena) + " m3");

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAreaLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaLosaActionPerformed

    private void txtVolumenLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumenLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumenLosaActionPerformed

    private void txtGravaLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGravaLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGravaLosaActionPerformed

    private void txtConcretoLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcretoLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcretoLosaActionPerformed

    private void txtVarillaLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarillaLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarillaLosaActionPerformed

    private void btnResetearMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearMuroActionPerformed

        txtLargoLosa.setText("");
        txtAnchoLosa.setText("");
        txtEspesorLosa.setText("");
        txtAreaLosa.setText("");
        txtVolumenLosa.setText("");
        txtConcretoLosa.setText("");
        txtVarillaLosa.setText("");
        txtCementoLosa.setText("");
        txtArenaLosa.setText("");
        txtGravaLosa.setText("");

        txtLargoLosa.requestFocus();
    }//GEN-LAST:event_btnResetearMuroActionPerformed

    private void txtArenaLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArenaLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArenaLosaActionPerformed

    private void txtCementoLosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCementoLosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCementoLosaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLosaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLosaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLosaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLosaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraLosaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetearMuro;
    private javax.swing.JLabel iconConcreto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAnchoLosa;
    private javax.swing.JLabel lblAreaLosa;
    private javax.swing.JLabel lblArenaLosa;
    private javax.swing.JLabel lblCementoLosa;
    private javax.swing.JLabel lblConcretoLosa;
    private javax.swing.JLabel lblEspesorLosa;
    private javax.swing.JLabel lblGravaLosa;
    private javax.swing.JLabel lblLargoLosa;
    private javax.swing.JLabel lblMaterialesLosa;
    private javax.swing.JLabel lblMuro;
    private javax.swing.JLabel lblSpcLosa;
    private javax.swing.JLabel lblVarillaLosa;
    private javax.swing.JLabel lblVolumenLosa;
    private javax.swing.JPanel pnlIngresarDMuro;
    private javax.swing.JPanel pnlMaterialesMuro;
    private javax.swing.JPanel pnlSpcMuro;
    private javax.swing.JTextField txtAnchoLosa;
    private javax.swing.JTextField txtAreaLosa;
    private javax.swing.JTextField txtArenaLosa;
    private javax.swing.JTextField txtCementoLosa;
    private javax.swing.JTextField txtConcretoLosa;
    private javax.swing.JTextField txtEspesorLosa;
    private javax.swing.JTextField txtGravaLosa;
    private javax.swing.JTextField txtLargoLosa;
    private javax.swing.JTextField txtVarillaLosa;
    private javax.swing.JTextField txtVolumenLosa;
    // End of variables declaration//GEN-END:variables
}
