/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;

/**
 *
 * @author omarf
 */
public class CalculadoraColumnaGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraColumnaRoC
     */
    public CalculadoraColumnaGUI() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRC = new javax.swing.ButtonGroup();
        pnlIngresarDColumna = new javax.swing.JPanel();
        txtAnchoDiametroColumna = new javax.swing.JTextField();
        lblAltoColumna = new javax.swing.JLabel();
        lblAnchoDiametroColumna = new javax.swing.JLabel();
        txtAltoColumna = new javax.swing.JTextField();
        lblColumna = new javax.swing.JLabel();
        lblLargoColumna = new javax.swing.JLabel();
        txtLargoColumna = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        rbtnRectangular = new javax.swing.JRadioButton();
        rbtnCircular = new javax.swing.JRadioButton();
        pnlSpcColumna = new javax.swing.JPanel();
        lblSpcColumna = new javax.swing.JLabel();
        lblAreaColumna = new javax.swing.JLabel();
        txtAreaColumna = new javax.swing.JTextField();
        lblVolumenColumna = new javax.swing.JLabel();
        txtVolumenColumna = new javax.swing.JTextField();
        pnlMaterialesColumna = new javax.swing.JPanel();
        lblMaterialesColumna = new javax.swing.JLabel();
        lblCementoColumna = new javax.swing.JLabel();
        txtGravaColumna = new javax.swing.JTextField();
        lblConcretoColumna = new javax.swing.JLabel();
        txtConcretoColumna = new javax.swing.JTextField();
        txtVarillaColumna = new javax.swing.JTextField();
        lblVarillaLosa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnResetearColumna = new javax.swing.JButton();
        lblArenaColumna = new javax.swing.JLabel();
        lblGravaColumna = new javax.swing.JLabel();
        txtArenaColumna = new javax.swing.JTextField();
        txtCementoColumna = new javax.swing.JTextField();
        iconConcreto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Calculadora de Columna");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIngresarDColumna.setBackground(new java.awt.Color(75, 75, 75));
        pnlIngresarDColumna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnchoDiametroColumna.setBackground(java.awt.Color.black);
        txtAnchoDiametroColumna.setForeground(java.awt.Color.white);
        pnlIngresarDColumna.add(txtAnchoDiametroColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 121, -1));

        lblAltoColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAltoColumna.setForeground(java.awt.Color.white);
        lblAltoColumna.setText("Alto de la columna (m):");
        pnlIngresarDColumna.add(lblAltoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lblAnchoDiametroColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAnchoDiametroColumna.setForeground(java.awt.Color.white);
        lblAnchoDiametroColumna.setText("Ancho de la columna (m):");
        pnlIngresarDColumna.add(lblAnchoDiametroColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        txtAltoColumna.setBackground(java.awt.Color.black);
        txtAltoColumna.setForeground(java.awt.Color.white);
        txtAltoColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltoColumnaActionPerformed(evt);
            }
        });
        pnlIngresarDColumna.add(txtAltoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 121, -1));

        lblColumna.setBackground(java.awt.Color.white);
        lblColumna.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblColumna.setForeground(java.awt.Color.white);
        lblColumna.setText("Calcular la cantidad de materiales para una columna");
        pnlIngresarDColumna.add(lblColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 50));

        lblLargoColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoColumna.setForeground(java.awt.Color.white);
        lblLargoColumna.setText("Largo de la columna (m):");
        pnlIngresarDColumna.add(lblLargoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtLargoColumna.setBackground(java.awt.Color.black);
        txtLargoColumna.setForeground(java.awt.Color.white);
        pnlIngresarDColumna.add(txtLargoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 121, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.setFocusable(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlIngresarDColumna.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, 37));

        buttonGroupRC.add(rbtnRectangular);
        rbtnRectangular.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        rbtnRectangular.setForeground(java.awt.Color.white);
        rbtnRectangular.setSelected(true);
        rbtnRectangular.setText("Rectangular");
        rbtnRectangular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRectangularActionPerformed(evt);
            }
        });
        pnlIngresarDColumna.add(rbtnRectangular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 120, -1));

        buttonGroupRC.add(rbtnCircular);
        rbtnCircular.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        rbtnCircular.setForeground(java.awt.Color.white);
        rbtnCircular.setText("Circular");
        rbtnCircular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCircularActionPerformed(evt);
            }
        });
        pnlIngresarDColumna.add(rbtnCircular, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 140, -1));

        getContentPane().add(pnlIngresarDColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 240));

        pnlSpcColumna.setBackground(new java.awt.Color(36, 36, 36));
        pnlSpcColumna.setPreferredSize(new java.awt.Dimension(300, 255));
        pnlSpcColumna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpcColumna.setBackground(java.awt.Color.white);
        lblSpcColumna.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblSpcColumna.setForeground(java.awt.Color.white);
        lblSpcColumna.setText("Específicaciones de la columna");
        pnlSpcColumna.add(lblSpcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 260, 50));

        lblAreaColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAreaColumna.setForeground(java.awt.Color.white);
        lblAreaColumna.setText("Área:");
        pnlSpcColumna.add(lblAreaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        txtAreaColumna.setEditable(false);
        txtAreaColumna.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaColumna.setForeground(java.awt.Color.white);
        txtAreaColumna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaColumnaActionPerformed(evt);
            }
        });
        pnlSpcColumna.add(txtAreaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 121, -1));

        lblVolumenColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVolumenColumna.setForeground(java.awt.Color.white);
        lblVolumenColumna.setText("Volumen:");
        pnlSpcColumna.add(lblVolumenColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        txtVolumenColumna.setEditable(false);
        txtVolumenColumna.setBackground(new java.awt.Color(0, 0, 0));
        txtVolumenColumna.setForeground(java.awt.Color.white);
        txtVolumenColumna.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVolumenColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumenColumnaActionPerformed(evt);
            }
        });
        pnlSpcColumna.add(txtVolumenColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 121, -1));

        getContentPane().add(pnlSpcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 310, 240));

        pnlMaterialesColumna.setBackground(new java.awt.Color(204, 204, 204));
        pnlMaterialesColumna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaterialesColumna.setBackground(java.awt.Color.white);
        lblMaterialesColumna.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMaterialesColumna.setText("Cantidad de materiales necesarios para levantar la columna");
        pnlMaterialesColumna.add(lblMaterialesColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 490, 64));

        lblCementoColumna.setBackground(new java.awt.Color(0, 0, 0));
        lblCementoColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblCementoColumna.setText("Cemento:");
        pnlMaterialesColumna.add(lblCementoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtGravaColumna.setBackground(java.awt.Color.black);
        txtGravaColumna.setForeground(java.awt.Color.white);
        txtGravaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGravaColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(txtGravaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        lblConcretoColumna.setBackground(new java.awt.Color(0, 0, 0));
        lblConcretoColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblConcretoColumna.setText("Concreto:");
        pnlMaterialesColumna.add(lblConcretoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtConcretoColumna.setBackground(java.awt.Color.black);
        txtConcretoColumna.setForeground(java.awt.Color.white);
        txtConcretoColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcretoColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(txtConcretoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        txtVarillaColumna.setBackground(java.awt.Color.black);
        txtVarillaColumna.setForeground(java.awt.Color.white);
        txtVarillaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarillaColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(txtVarillaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        lblVarillaLosa.setBackground(new java.awt.Color(0, 0, 0));
        lblVarillaLosa.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVarillaLosa.setText("Varilla:");
        pnlMaterialesColumna.add(lblVarillaLosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arena.png"))); // NOI18N
        pnlMaterialesColumna.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemento.png"))); // NOI18N
        pnlMaterialesColumna.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 40));

        btnResetearColumna.setBackground(new java.awt.Color(255, 86, 86));
        btnResetearColumna.setText("RESETEAR");
        btnResetearColumna.setFocusable(false);
        btnResetearColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(btnResetearColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 40));

        lblArenaColumna.setBackground(new java.awt.Color(0, 0, 0));
        lblArenaColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblArenaColumna.setText("Arena:");
        pnlMaterialesColumna.add(lblArenaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblGravaColumna.setBackground(new java.awt.Color(0, 0, 0));
        lblGravaColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblGravaColumna.setText("Grava:");
        pnlMaterialesColumna.add(lblGravaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtArenaColumna.setBackground(java.awt.Color.black);
        txtArenaColumna.setForeground(java.awt.Color.white);
        txtArenaColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArenaColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(txtArenaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        txtCementoColumna.setBackground(java.awt.Color.black);
        txtCementoColumna.setForeground(java.awt.Color.white);
        txtCementoColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCementoColumnaActionPerformed(evt);
            }
        });
        pnlMaterialesColumna.add(txtCementoColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));

        iconConcreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Concreto.png"))); // NOI18N
        pnlMaterialesColumna.add(iconConcreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Varilla.png"))); // NOI18N
        pnlMaterialesColumna.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grava.png"))); // NOI18N
        pnlMaterialesColumna.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Columna.png"))); // NOI18N
        pnlMaterialesColumna.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        getContentPane().add(pnlMaterialesColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 810, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltoColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltoColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltoColumnaActionPerformed


    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        CalculadoraMateriales c = new CalculadoraMateriales();

        // Codigo para columna rectangular
        if (rbtnRectangular.isSelected()) {

            // Calculamos el area
            double area = c.calcularArea(Double.parseDouble(txtAltoColumna.getText()), Double.parseDouble(txtLargoColumna.getText()));
            txtAreaColumna.setText(area + " m2");

            // Calculamos el volumen
            double volumen = c.calcularVolumen(Double.parseDouble(txtAreaColumna.getText().replace(" m2", "").trim()), Double.parseDouble(txtAnchoDiametroColumna.getText()));
            txtVolumenColumna.setText(volumen + " m3");

            // Calculamos materiales
            // Calculo de concreto es directamente igual al volumen
            txtConcretoColumna.setText(txtVolumenColumna.getText());

            DecimalFormat df = new DecimalFormat("#.00");

            // Calculo de varilla
            double varilla = c.calcularVarillaColumna(Double.parseDouble(txtAreaColumna.getText().replace(" m2", "").trim()));
            txtVarillaColumna.setText(varilla + " kg");

            // Calculo del cemento
            double cemento = c.calcularCementoLosa(Double.parseDouble(txtVolumenColumna.getText().replace(" m3", "").trim()));
            txtCementoColumna.setText(df.format(cemento) + " sacos");

            // Calculo de arena
            double arena = c.calcularArena(Double.parseDouble(txtVolumenColumna.getText().replace(" m3", "").trim()));
            txtArenaColumna.setText(df.format(arena) + " m3");

            // Calculo de grava, mismo que arena
            txtGravaColumna.setText(df.format(arena) + " m3");

        }

        if (rbtnCircular.isSelected()) {

            DecimalFormat df2 = new DecimalFormat("#.00");

            // Calculamos el area
            double area = c.calcularAreaColumnaC(Double.parseDouble(txtAnchoDiametroColumna.getText()));
            txtAreaColumna.setText(df2.format(area) + " m2");

            // Calculamos el volumen
            double volumen = c.calcularVolumen(Double.parseDouble(txtAreaColumna.getText().replace(" m2", "").trim()), Double.parseDouble(txtAnchoDiametroColumna.getText()));
            txtVolumenColumna.setText(volumen + " m3");

            // Calcular materiales
            // Calculo de concreto, es directamente igual al volumen
            txtConcretoColumna.setText(txtVolumenColumna.getText());

            // Calculo de varilla
            double varilla = c.calcularVarillaColumna(Double.parseDouble(txtAreaColumna.getText().replace(" m2", "").trim()));
            txtVarillaColumna.setText(df2.format(varilla) + " kg");

            // Calculo del cemento
            double cemento = c.calcularCementoLosa(Double.parseDouble(txtVolumenColumna.getText().replace(" m3", "").trim()));
            txtCementoColumna.setText(df2.format(cemento) + " sacos");

            // Calculo de arena
            double arena = c.calcularArena(Double.parseDouble(txtVolumenColumna.getText().replace(" m3", "").trim()));
            txtArenaColumna.setText(df2.format(arena) + " m3");

            // Calculo de grava, mismo que arena
            txtGravaColumna.setText(df2.format(arena) + " m3");

        }

    }//GEN-LAST:event_btnCalcularActionPerformed

    // Se encarga de mostrar sola la parte correspondiente a la columna rectangular
    private void rbtnRectangularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRectangularActionPerformed

        lblAnchoDiametroColumna.setText("Ancho de la columna: ");
        lblLargoColumna.setVisible(true);
        txtLargoColumna.setVisible(true);

    }//GEN-LAST:event_rbtnRectangularActionPerformed

    // Se encarga de mostrar sola la parte correspondiente a la columna rectangular
    private void rbtnCircularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCircularActionPerformed

        lblAnchoDiametroColumna.setText("Diámetro de la columna: ");
        lblLargoColumna.setVisible(false);
        txtLargoColumna.setVisible(false);
    }//GEN-LAST:event_rbtnCircularActionPerformed

    private void txtAreaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaColumnaActionPerformed

    private void txtVolumenColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumenColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumenColumnaActionPerformed

    private void txtGravaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGravaColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGravaColumnaActionPerformed

    private void txtConcretoColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcretoColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcretoColumnaActionPerformed

    private void txtVarillaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarillaColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarillaColumnaActionPerformed

    private void btnResetearColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearColumnaActionPerformed

        txtLargoColumna.setText("");
        txtAnchoDiametroColumna.setText("");
        txtAltoColumna.setText("");
        txtAreaColumna.setText("");
        txtVolumenColumna.setText("");
        txtConcretoColumna.setText("");
        txtVarillaColumna.setText("");
        txtCementoColumna.setText("");
        txtArenaColumna.setText("");
        txtGravaColumna.setText("");

        txtAltoColumna.requestFocus();

    }//GEN-LAST:event_btnResetearColumnaActionPerformed

    private void txtArenaColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArenaColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArenaColumnaActionPerformed

    private void txtCementoColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCementoColumnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCementoColumnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraColumnaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraColumnaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraColumnaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraColumnaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraColumnaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetearColumna;
    private javax.swing.ButtonGroup buttonGroupRC;
    private javax.swing.JLabel iconConcreto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAltoColumna;
    private javax.swing.JLabel lblAnchoDiametroColumna;
    private javax.swing.JLabel lblAreaColumna;
    private javax.swing.JLabel lblArenaColumna;
    private javax.swing.JLabel lblCementoColumna;
    private javax.swing.JLabel lblColumna;
    private javax.swing.JLabel lblConcretoColumna;
    private javax.swing.JLabel lblGravaColumna;
    private javax.swing.JLabel lblLargoColumna;
    private javax.swing.JLabel lblMaterialesColumna;
    private javax.swing.JLabel lblSpcColumna;
    private javax.swing.JLabel lblVarillaLosa;
    private javax.swing.JLabel lblVolumenColumna;
    private javax.swing.JPanel pnlIngresarDColumna;
    private javax.swing.JPanel pnlMaterialesColumna;
    private javax.swing.JPanel pnlSpcColumna;
    private javax.swing.JRadioButton rbtnCircular;
    private javax.swing.JRadioButton rbtnRectangular;
    private javax.swing.JTextField txtAltoColumna;
    private javax.swing.JTextField txtAnchoDiametroColumna;
    private javax.swing.JTextField txtAreaColumna;
    private javax.swing.JTextField txtArenaColumna;
    private javax.swing.JTextField txtCementoColumna;
    private javax.swing.JTextField txtConcretoColumna;
    private javax.swing.JTextField txtGravaColumna;
    private javax.swing.JTextField txtLargoColumna;
    private javax.swing.JTextField txtVarillaColumna;
    private javax.swing.JTextField txtVolumenColumna;
    // End of variables declaration//GEN-END:variables
}
