/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
/**
 *
 * @author omarf
 */
public class CalculadoraMuroGUI extends javax.swing.JFrame {

    public CalculadoraMuroGUI() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMaterialesMuro = new javax.swing.JPanel();
        lblMaterialesMuro = new javax.swing.JLabel();
        lblCementoMuro = new javax.swing.JLabel();
        txtCementoMuro = new javax.swing.JTextField();
        lblBlocksMuro = new javax.swing.JLabel();
        txtBlocksMuro = new javax.swing.JTextField();
        txtArenaMuro = new javax.swing.JTextField();
        lblArenaMuro1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnResetearMuro = new javax.swing.JButton();
        pnlSpcMuro = new javax.swing.JPanel();
        lblSpcMuro = new javax.swing.JLabel();
        lblAreaMuro = new javax.swing.JLabel();
        txtAreaMuro = new javax.swing.JTextField();
        lblVolumenMuro = new javax.swing.JLabel();
        txtVolumenMuro = new javax.swing.JTextField();
        pnlIngresarDMuro = new javax.swing.JPanel();
        txtLargoMuro = new javax.swing.JTextField();
        lblLargoMuro = new javax.swing.JLabel();
        lblLargoMuro1 = new javax.swing.JLabel();
        txtAltoMuro = new javax.swing.JTextField();
        lblMuro = new javax.swing.JLabel();
        lblLargoMuro2 = new javax.swing.JLabel();
        txtEspesorMuro = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Calculadora de Muro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMaterialesMuro.setBackground(new java.awt.Color(204, 204, 204));
        pnlMaterialesMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaterialesMuro.setBackground(java.awt.Color.white);
        lblMaterialesMuro.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMaterialesMuro.setText("Cantidad de materiales necesarios para levantar el muro");
        pnlMaterialesMuro.add(lblMaterialesMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 470, 64));

        lblCementoMuro.setBackground(new java.awt.Color(0, 0, 0));
        lblCementoMuro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblCementoMuro.setText("Cemento:");
        pnlMaterialesMuro.add(lblCementoMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtCementoMuro.setBackground(java.awt.Color.black);
        txtCementoMuro.setForeground(java.awt.Color.white);
        txtCementoMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCementoMuroActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtCementoMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));

        lblBlocksMuro.setBackground(new java.awt.Color(0, 0, 0));
        lblBlocksMuro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblBlocksMuro.setText("Blocks:");
        pnlMaterialesMuro.add(lblBlocksMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtBlocksMuro.setBackground(java.awt.Color.black);
        txtBlocksMuro.setForeground(java.awt.Color.white);
        txtBlocksMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlocksMuroActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtBlocksMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        txtArenaMuro.setBackground(java.awt.Color.black);
        txtArenaMuro.setForeground(java.awt.Color.white);
        txtArenaMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArenaMuroActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(txtArenaMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        lblArenaMuro1.setBackground(new java.awt.Color(0, 0, 0));
        lblArenaMuro1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblArenaMuro1.setText("Arena:");
        pnlMaterialesMuro.add(lblArenaMuro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Muro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnlMaterialesMuro.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Blocks.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arena.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemento.png"))); // NOI18N
        pnlMaterialesMuro.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 40));

        btnResetearMuro.setBackground(new java.awt.Color(255, 86, 86));
        btnResetearMuro.setText("RESETEAR");
        btnResetearMuro.setFocusable(false);
        btnResetearMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearMuroActionPerformed(evt);
            }
        });
        pnlMaterialesMuro.add(btnResetearMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, 40));

        getContentPane().add(pnlMaterialesMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 720, 230));

        pnlSpcMuro.setBackground(new java.awt.Color(36, 36, 36));
        pnlSpcMuro.setPreferredSize(new java.awt.Dimension(300, 255));
        pnlSpcMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpcMuro.setBackground(java.awt.Color.white);
        lblSpcMuro.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblSpcMuro.setForeground(java.awt.Color.white);
        lblSpcMuro.setText("Específicaciones del muro");
        pnlSpcMuro.add(lblSpcMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, 220, 61));

        lblAreaMuro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAreaMuro.setForeground(java.awt.Color.white);
        lblAreaMuro.setText("Área:");
        pnlSpcMuro.add(lblAreaMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 67, -1, -1));

        txtAreaMuro.setEditable(false);
        txtAreaMuro.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaMuro.setForeground(java.awt.Color.white);
        txtAreaMuro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaMuroActionPerformed(evt);
            }
        });
        pnlSpcMuro.add(txtAreaMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 93, 121, -1));

        lblVolumenMuro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVolumenMuro.setForeground(java.awt.Color.white);
        lblVolumenMuro.setText("Volumen:");
        pnlSpcMuro.add(lblVolumenMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 131, -1, -1));

        txtVolumenMuro.setEditable(false);
        txtVolumenMuro.setBackground(new java.awt.Color(0, 0, 0));
        txtVolumenMuro.setForeground(java.awt.Color.white);
        txtVolumenMuro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVolumenMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumenMuroActionPerformed(evt);
            }
        });
        pnlSpcMuro.add(txtVolumenMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 157, 121, -1));

        getContentPane().add(pnlSpcMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 310, 260));

        pnlIngresarDMuro.setBackground(new java.awt.Color(75, 75, 75));
        pnlIngresarDMuro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLargoMuro.setBackground(java.awt.Color.black);
        txtLargoMuro.setForeground(java.awt.Color.white);
        pnlIngresarDMuro.add(txtLargoMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 108, 121, -1));

        lblLargoMuro.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoMuro.setForeground(java.awt.Color.white);
        lblLargoMuro.setText("Alto del muro (m):");
        pnlIngresarDMuro.add(lblLargoMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, -1, -1));

        lblLargoMuro1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoMuro1.setForeground(java.awt.Color.white);
        lblLargoMuro1.setText("Largo del muro (m):");
        pnlIngresarDMuro.add(lblLargoMuro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 110, -1, -1));

        txtAltoMuro.setBackground(java.awt.Color.black);
        txtAltoMuro.setForeground(java.awt.Color.white);
        txtAltoMuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltoMuroActionPerformed(evt);
            }
        });
        pnlIngresarDMuro.add(txtAltoMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 121, -1));

        lblMuro.setBackground(java.awt.Color.white);
        lblMuro.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMuro.setForeground(java.awt.Color.white);
        lblMuro.setText("Calcular la cantidad de materiales para un muro");
        pnlIngresarDMuro.add(lblMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 64));

        lblLargoMuro2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoMuro2.setForeground(java.awt.Color.white);
        lblLargoMuro2.setText("Espesor del muro (m):");
        pnlIngresarDMuro.add(lblLargoMuro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 154, -1, -1));

        txtEspesorMuro.setBackground(java.awt.Color.black);
        txtEspesorMuro.setForeground(java.awt.Color.white);
        pnlIngresarDMuro.add(txtEspesorMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 152, 121, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.setFocusable(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlIngresarDMuro.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 120, 37));

        getContentPane().add(pnlIngresarDMuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAltoMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltoMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltoMuroActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        DecimalFormat df = new DecimalFormat("#.00");

        // Calcular especificaciones
        // Instancia la clase y calcula el area primero
        CalculadoraMateriales m = new CalculadoraMateriales();
        double area = m.calcularAreaMuro(Double.parseDouble(txtLargoMuro.getText()), Double.parseDouble(txtAltoMuro.getText()));
        txtAreaMuro.setText(area + " m2");

        // Luego el volumen
        double volumen = m.calcularVolumen(Double.parseDouble(txtAreaMuro.getText().replace(" m2", "").trim()), Double.parseDouble(txtEspesorMuro.getText()));
        txtVolumenMuro.setText(df.format(volumen) + " m3");

        // Calcular materiales
        // Calculo de blocks
        double blocks = m.calcularBlocks(Double.parseDouble(txtAreaMuro.getText().replace(" m2", "").trim()));
        txtBlocksMuro.setText((int) blocks + " Unidades");

        // Calculo de sacos de arena
        double arena = m.calcularArena(Double.parseDouble(txtVolumenMuro.getText().replace(" m3", "").trim()));
        txtArenaMuro.setText(df.format(arena) + " m3");

        // Calculo de sacos de cemento
        double cemento = m.calcularCementoMuro(Double.parseDouble(txtVolumenMuro.getText().replace(" m3", "").trim()));
        txtCementoMuro.setText(df.format(cemento) + " Sacos");

    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAreaMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaMuroActionPerformed

    private void txtVolumenMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumenMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumenMuroActionPerformed

    private void txtCementoMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCementoMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCementoMuroActionPerformed

    private void txtBlocksMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlocksMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlocksMuroActionPerformed

    private void txtArenaMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArenaMuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArenaMuroActionPerformed

    /**
     * Resetea todos los campos del Form del muro
     *
     * @param evt
     */
    private void btnResetearMuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearMuroActionPerformed

        txtAltoMuro.setText("");
        txtLargoMuro.setText("");
        txtEspesorMuro.setText("");
        txtAreaMuro.setText("");
        txtVolumenMuro.setText("");
        txtBlocksMuro.setText("");
        txtArenaMuro.setText("");
        txtCementoMuro.setText("");
        txtAltoMuro.requestFocus();
    }//GEN-LAST:event_btnResetearMuroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMuroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMuroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMuroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraMuroGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetearMuro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAreaMuro;
    private javax.swing.JLabel lblArenaMuro1;
    private javax.swing.JLabel lblBlocksMuro;
    private javax.swing.JLabel lblCementoMuro;
    private javax.swing.JLabel lblLargoMuro;
    private javax.swing.JLabel lblLargoMuro1;
    private javax.swing.JLabel lblLargoMuro2;
    private javax.swing.JLabel lblMaterialesMuro;
    private javax.swing.JLabel lblMuro;
    private javax.swing.JLabel lblSpcMuro;
    private javax.swing.JLabel lblVolumenMuro;
    private javax.swing.JPanel pnlIngresarDMuro;
    private javax.swing.JPanel pnlMaterialesMuro;
    private javax.swing.JPanel pnlSpcMuro;
    private javax.swing.JTextField txtAltoMuro;
    private javax.swing.JTextField txtAreaMuro;
    private javax.swing.JTextField txtArenaMuro;
    private javax.swing.JTextField txtBlocksMuro;
    private javax.swing.JTextField txtCementoMuro;
    private javax.swing.JTextField txtEspesorMuro;
    private javax.swing.JTextField txtLargoMuro;
    private javax.swing.JTextField txtVolumenMuro;
    // End of variables declaration//GEN-END:variables
}
