/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;

/**
 *
 * @author omarf
 */
public class CalculadoraCimientoGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraCimientoGUI
     */
    public CalculadoraCimientoGUI() {
        initComponents();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlIngresarDCimiento = new javax.swing.JPanel();
        txtAnchoCimiento = new javax.swing.JTextField();
        lblProfundidadCimiento = new javax.swing.JLabel();
        lblAnchoCimiento = new javax.swing.JLabel();
        txtProfundidadCimiento = new javax.swing.JTextField();
        lblCimiento = new javax.swing.JLabel();
        lblLargoCimiento = new javax.swing.JLabel();
        txtLargoCimiento = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        pnlSpcColumna = new javax.swing.JPanel();
        lblSpcColumna = new javax.swing.JLabel();
        lblAreaColumna = new javax.swing.JLabel();
        txtAreaCimiento = new javax.swing.JTextField();
        lblVolumenColumna = new javax.swing.JLabel();
        txtVolumenCimiento = new javax.swing.JTextField();
        pnlMaterialesCimiento = new javax.swing.JPanel();
        lblMaterialesCimiento = new javax.swing.JLabel();
        lblCementoCimiento = new javax.swing.JLabel();
        txtGravaCimiento = new javax.swing.JTextField();
        lblConcretoCimiento = new javax.swing.JLabel();
        txtConcretoCimiento = new javax.swing.JTextField();
        txtVarillaCimiento = new javax.swing.JTextField();
        lblVarillaCimiento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnResetearCimiento = new javax.swing.JButton();
        lblArenaCimiento = new javax.swing.JLabel();
        lblGravaCimiento = new javax.swing.JLabel();
        txtArenaCimiento = new javax.swing.JTextField();
        txtCementoCimiento = new javax.swing.JTextField();
        iconConcreto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Calculadora de Cimiento");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIngresarDCimiento.setBackground(new java.awt.Color(75, 75, 75));
        pnlIngresarDCimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnchoCimiento.setBackground(java.awt.Color.black);
        txtAnchoCimiento.setForeground(java.awt.Color.white);
        pnlIngresarDCimiento.add(txtAnchoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 121, -1));

        lblProfundidadCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblProfundidadCimiento.setForeground(java.awt.Color.white);
        lblProfundidadCimiento.setText("Profundidad del cimiento (m):");
        pnlIngresarDCimiento.add(lblProfundidadCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblAnchoCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAnchoCimiento.setForeground(java.awt.Color.white);
        lblAnchoCimiento.setText("Ancho del cimiento (m):");
        pnlIngresarDCimiento.add(lblAnchoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtProfundidadCimiento.setBackground(java.awt.Color.black);
        txtProfundidadCimiento.setForeground(java.awt.Color.white);
        txtProfundidadCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProfundidadCimientoActionPerformed(evt);
            }
        });
        pnlIngresarDCimiento.add(txtProfundidadCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 121, -1));

        lblCimiento.setBackground(java.awt.Color.white);
        lblCimiento.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblCimiento.setForeground(java.awt.Color.white);
        lblCimiento.setText("Calcular la cantidad de materiales para un cimiento");
        pnlIngresarDCimiento.add(lblCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 50));

        lblLargoCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLargoCimiento.setForeground(java.awt.Color.white);
        lblLargoCimiento.setText("Largo del cimiento (m):");
        pnlIngresarDCimiento.add(lblLargoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtLargoCimiento.setBackground(java.awt.Color.black);
        txtLargoCimiento.setForeground(java.awt.Color.white);
        pnlIngresarDCimiento.add(txtLargoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 121, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.setFocusable(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlIngresarDCimiento.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 120, 37));

        getContentPane().add(pnlIngresarDCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 240));

        pnlSpcColumna.setBackground(new java.awt.Color(36, 36, 36));
        pnlSpcColumna.setPreferredSize(new java.awt.Dimension(300, 255));
        pnlSpcColumna.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSpcColumna.setBackground(java.awt.Color.white);
        lblSpcColumna.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblSpcColumna.setForeground(java.awt.Color.white);
        lblSpcColumna.setText("Específicaciones del cimiento");
        pnlSpcColumna.add(lblSpcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 260, 50));

        lblAreaColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAreaColumna.setForeground(java.awt.Color.white);
        lblAreaColumna.setText("Área:");
        pnlSpcColumna.add(lblAreaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        txtAreaCimiento.setEditable(false);
        txtAreaCimiento.setBackground(new java.awt.Color(0, 0, 0));
        txtAreaCimiento.setForeground(java.awt.Color.white);
        txtAreaCimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAreaCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaCimientoActionPerformed(evt);
            }
        });
        pnlSpcColumna.add(txtAreaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 121, -1));

        lblVolumenColumna.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVolumenColumna.setForeground(java.awt.Color.white);
        lblVolumenColumna.setText("Volumen:");
        pnlSpcColumna.add(lblVolumenColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        txtVolumenCimiento.setEditable(false);
        txtVolumenCimiento.setBackground(new java.awt.Color(0, 0, 0));
        txtVolumenCimiento.setForeground(java.awt.Color.white);
        txtVolumenCimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtVolumenCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVolumenCimientoActionPerformed(evt);
            }
        });
        pnlSpcColumna.add(txtVolumenCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 121, -1));

        getContentPane().add(pnlSpcColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 370, 240));

        pnlMaterialesCimiento.setBackground(new java.awt.Color(204, 204, 204));
        pnlMaterialesCimiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaterialesCimiento.setBackground(java.awt.Color.white);
        lblMaterialesCimiento.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 18)); // NOI18N
        lblMaterialesCimiento.setText("Cantidad de materiales necesarios para levantar el cimiento");
        pnlMaterialesCimiento.add(lblMaterialesCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 490, 64));

        lblCementoCimiento.setBackground(new java.awt.Color(0, 0, 0));
        lblCementoCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblCementoCimiento.setText("Cemento:");
        pnlMaterialesCimiento.add(lblCementoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        txtGravaCimiento.setBackground(java.awt.Color.black);
        txtGravaCimiento.setForeground(java.awt.Color.white);
        txtGravaCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGravaCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(txtGravaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        lblConcretoCimiento.setBackground(new java.awt.Color(0, 0, 0));
        lblConcretoCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblConcretoCimiento.setText("Concreto:");
        pnlMaterialesCimiento.add(lblConcretoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtConcretoCimiento.setBackground(java.awt.Color.black);
        txtConcretoCimiento.setForeground(java.awt.Color.white);
        txtConcretoCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConcretoCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(txtConcretoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        txtVarillaCimiento.setBackground(java.awt.Color.black);
        txtVarillaCimiento.setForeground(java.awt.Color.white);
        txtVarillaCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVarillaCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(txtVarillaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, -1));

        lblVarillaCimiento.setBackground(new java.awt.Color(0, 0, 0));
        lblVarillaCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblVarillaCimiento.setText("Varilla:");
        pnlMaterialesCimiento.add(lblVarillaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Arena.png"))); // NOI18N
        pnlMaterialesCimiento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cemento.png"))); // NOI18N
        pnlMaterialesCimiento.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 40));

        btnResetearCimiento.setBackground(new java.awt.Color(255, 86, 86));
        btnResetearCimiento.setText("RESETEAR");
        btnResetearCimiento.setFocusable(false);
        btnResetearCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetearCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(btnResetearCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 40));

        lblArenaCimiento.setBackground(new java.awt.Color(0, 0, 0));
        lblArenaCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblArenaCimiento.setText("Arena:");
        pnlMaterialesCimiento.add(lblArenaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        lblGravaCimiento.setBackground(new java.awt.Color(0, 0, 0));
        lblGravaCimiento.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblGravaCimiento.setText("Grava:");
        pnlMaterialesCimiento.add(lblGravaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtArenaCimiento.setBackground(java.awt.Color.black);
        txtArenaCimiento.setForeground(java.awt.Color.white);
        txtArenaCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArenaCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(txtArenaCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 180, -1));

        txtCementoCimiento.setBackground(java.awt.Color.black);
        txtCementoCimiento.setForeground(java.awt.Color.white);
        txtCementoCimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCementoCimientoActionPerformed(evt);
            }
        });
        pnlMaterialesCimiento.add(txtCementoCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 180, -1));

        iconConcreto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Concreto.png"))); // NOI18N
        pnlMaterialesCimiento.add(iconConcreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Varilla.png"))); // NOI18N
        pnlMaterialesCimiento.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grava.png"))); // NOI18N
        pnlMaterialesCimiento.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cimiento.png"))); // NOI18N
        pnlMaterialesCimiento.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        getContentPane().add(pnlMaterialesCimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 810, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProfundidadCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProfundidadCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProfundidadCimientoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        CalculadoraMateriales ci = new CalculadoraMateriales();

        // Calculamos el area
        double area = ci.calcularArea(Double.parseDouble(txtLargoCimiento.getText()), Double.parseDouble(txtAnchoCimiento.getText()));
        txtAreaCimiento.setText(area + " m2");

        // Calculamos el volumen
        double volumen = ci.calcularVolumen(Double.parseDouble(txtAreaCimiento.getText().replace(" m2", "").trim()), Double.parseDouble(txtProfundidadCimiento.getText()));
        txtVolumenCimiento.setText(volumen + " m3");

        DecimalFormat df = new DecimalFormat("#.00");

        // Calculamos materiales
        // Calculo de concreto
        double concreto = ci.calcularConcretoCimiento(Double.parseDouble(txtLargoCimiento.getText()), Double.parseDouble(txtAnchoCimiento.getText()), Double.parseDouble(txtProfundidadCimiento.getText()));
        txtConcretoCimiento.setText(df.format(concreto) + " m3");

        // Calculo de varilla
        double varilla = ci.calcularVarillaCimiento(Double.parseDouble(txtAreaCimiento.getText().replace(" m2", "").trim()));
        txtVarillaCimiento.setText(varilla + " kg");

        // Calculo del cemento
        double cemento = ci.calcularCementoCimiento(Double.parseDouble(txtVolumenCimiento.getText().replace(" m3", "").trim()));
        txtCementoCimiento.setText(df.format(cemento) + " sacos");

        // Calculo de arena
        double arena = ci.calcularArena(Double.parseDouble(txtVolumenCimiento.getText().replace(" m3", "").trim()));
        txtArenaCimiento.setText(df.format(arena) + " m3");

        // Calculo de grava, mismo que arena
        txtGravaCimiento.setText(df.format(arena) + " m3");


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtAreaCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaCimientoActionPerformed

    private void txtVolumenCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVolumenCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVolumenCimientoActionPerformed

    private void txtGravaCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGravaCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGravaCimientoActionPerformed

    private void txtConcretoCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConcretoCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConcretoCimientoActionPerformed

    private void txtVarillaCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVarillaCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVarillaCimientoActionPerformed

    private void btnResetearCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetearCimientoActionPerformed

        txtLargoCimiento.setText("");
        txtAnchoCimiento.setText("");
        txtProfundidadCimiento.setText("");
        txtAreaCimiento.setText("");
        txtVolumenCimiento.setText("");
        txtConcretoCimiento.setText("");
        txtVarillaCimiento.setText("");
        txtCementoCimiento.setText("");
        txtArenaCimiento.setText("");
        txtGravaCimiento.setText("");

        txtLargoCimiento.requestFocus();

    }//GEN-LAST:event_btnResetearCimientoActionPerformed

    private void txtArenaCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArenaCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArenaCimientoActionPerformed

    private void txtCementoCimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCementoCimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCementoCimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraCimientoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraCimientoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnResetearCimiento;
    private javax.swing.JLabel iconConcreto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblAnchoCimiento;
    private javax.swing.JLabel lblAreaColumna;
    private javax.swing.JLabel lblArenaCimiento;
    private javax.swing.JLabel lblCementoCimiento;
    private javax.swing.JLabel lblCimiento;
    private javax.swing.JLabel lblConcretoCimiento;
    private javax.swing.JLabel lblGravaCimiento;
    private javax.swing.JLabel lblLargoCimiento;
    private javax.swing.JLabel lblMaterialesCimiento;
    private javax.swing.JLabel lblProfundidadCimiento;
    private javax.swing.JLabel lblSpcColumna;
    private javax.swing.JLabel lblVarillaCimiento;
    private javax.swing.JLabel lblVolumenColumna;
    private javax.swing.JPanel pnlIngresarDCimiento;
    private javax.swing.JPanel pnlMaterialesCimiento;
    private javax.swing.JPanel pnlSpcColumna;
    private javax.swing.JTextField txtAnchoCimiento;
    private javax.swing.JTextField txtAreaCimiento;
    private javax.swing.JTextField txtArenaCimiento;
    private javax.swing.JTextField txtCementoCimiento;
    private javax.swing.JTextField txtConcretoCimiento;
    private javax.swing.JTextField txtGravaCimiento;
    private javax.swing.JTextField txtLargoCimiento;
    private javax.swing.JTextField txtProfundidadCimiento;
    private javax.swing.JTextField txtVarillaCimiento;
    private javax.swing.JTextField txtVolumenCimiento;
    // End of variables declaration//GEN-END:variables
}
