/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

/**
 *
 * @author Geison Medina
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableJob = new javax.swing.JPanel();
        inputCorreoLogin = new javax.swing.JTextField();
        enlaceRegisterLogin = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonInitLogin = new javax.swing.JLabel();
        inputPasswordLogin = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableJob.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputCorreoLogin.setBackground(new java.awt.Color(0, 0, 0));
        inputCorreoLogin.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        inputCorreoLogin.setForeground(new java.awt.Color(153, 153, 153));
        inputCorreoLogin.setText("Correo");
        inputCorreoLogin.setBorder(null);
        tableJob.add(inputCorreoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 290, 20));

        enlaceRegisterLogin.setBackground(new java.awt.Color(51, 51, 255));
        enlaceRegisterLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        enlaceRegisterLogin.setForeground(new java.awt.Color(204, 255, 255));
        enlaceRegisterLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enlaceRegisterLogin.setText("¿No tienes cuenta? Regístrate");
        enlaceRegisterLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        enlaceRegisterLogin.setFocusCycleRoot(true);
        enlaceRegisterLogin.setFocusTraversalPolicyProvider(true);
        tableJob.add(enlaceRegisterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 280, -1));
        tableJob.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 190, 20));

        buttonInitLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        buttonInitLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonInitLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonInitLogin.setText("Iniciar sesión");
        buttonInitLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableJob.add(buttonInitLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 300, 60));

        inputPasswordLogin.setBackground(new java.awt.Color(0, 0, 0));
        inputPasswordLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputPasswordLogin.setForeground(new java.awt.Color(153, 153, 153));
        inputPasswordLogin.setText("jPasswordField1");
        inputPasswordLogin.setBorder(null);
        tableJob.add(inputPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 400, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/marco9.gif"))); // NOI18N
        tableJob.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableJob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonInitLogin;
    private javax.swing.JLabel enlaceRegisterLogin;
    private javax.swing.JTextField inputCorreoLogin;
    private javax.swing.JPasswordField inputPasswordLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel tableJob;
    // End of variables declaration//GEN-END:variables
}
