/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import java.sql.ResultSet;
import java.sql.Statement;
import conectDB.conectMysql;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author Geison Medina
 */
public class Register extends javax.swing.JFrame {
    conectMysql con = new conectMysql();
    Connection cn = con.conectar();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enlaceBackRegister = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonRegister = new javax.swing.JLabel();
        inputCorreoRegister = new javax.swing.JTextField();
        inputNamesRegister = new javax.swing.JTextField();
        inputTelRegister = new javax.swing.JFormattedTextField();
        inputPasswordConfirmRegister = new javax.swing.JPasswordField();
        inputPasswordRegister = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enlaceBackRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        enlaceBackRegister.setForeground(new java.awt.Color(255, 255, 255));
        enlaceBackRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enlaceBackRegister.setText("Volver a Accesso");
        enlaceBackRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(enlaceBackRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 650, 120, 20));

        buttonRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        buttonRegister.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonRegister.setText("Registrar");
        buttonRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(buttonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 562, 300, 50));

        inputCorreoRegister.setBackground(new java.awt.Color(0, 0, 0));
        inputCorreoRegister.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        inputCorreoRegister.setForeground(new java.awt.Color(153, 153, 153));
        inputCorreoRegister.setText("Correo");
        inputCorreoRegister.setBorder(null);
        inputCorreoRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCorreoRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(inputCorreoRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 290, 30));

        inputNamesRegister.setBackground(new java.awt.Color(0, 0, 0));
        inputNamesRegister.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        inputNamesRegister.setForeground(new java.awt.Color(153, 153, 153));
        inputNamesRegister.setText("Nombre y Apellido");
        inputNamesRegister.setBorder(null);
        inputNamesRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamesRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(inputNamesRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 182, 290, 30));

        inputTelRegister.setBackground(new java.awt.Color(0, 0, 0));
        inputTelRegister.setBorder(null);
        inputTelRegister.setForeground(new java.awt.Color(153, 153, 153));
        inputTelRegister.setText("Telefono");
        inputTelRegister.setFont(new java.awt.Font("Segoe UI", 2, 16)); // NOI18N
        jPanel1.add(inputTelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 290, 30));

        inputPasswordConfirmRegister.setBackground(new java.awt.Color(0, 0, 0));
        inputPasswordConfirmRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputPasswordConfirmRegister.setForeground(new java.awt.Color(153, 153, 153));
        inputPasswordConfirmRegister.setText("jPasswordField1");
        inputPasswordConfirmRegister.setBorder(null);
        jPanel1.add(inputPasswordConfirmRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 290, 30));

        inputPasswordRegister.setBackground(new java.awt.Color(0, 0, 0));
        inputPasswordRegister.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        inputPasswordRegister.setForeground(new java.awt.Color(153, 153, 153));
        inputPasswordRegister.setText("jPasswordField1");
        inputPasswordRegister.setBorder(null);
        jPanel1.add(inputPasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/marco7.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCorreoRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCorreoRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCorreoRegisterActionPerformed

    private void inputNamesRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamesRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamesRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonRegister;
    private javax.swing.JLabel enlaceBackRegister;
    private javax.swing.JTextField inputCorreoRegister;
    private javax.swing.JTextField inputNamesRegister;
    private javax.swing.JPasswordField inputPasswordConfirmRegister;
    private javax.swing.JPasswordField inputPasswordRegister;
    private javax.swing.JFormattedTextField inputTelRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void showData() {
        String consultaSQL = "select * from users";
        System.out.println();
        String data[] = new String[6];

        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultaSQL);
            while (rs.next()) {
                data[0] = rs.getString(2);
            }

            System.err.println(data[0] + "nada");
        } catch (SQLException e) {
            System.out.println("Error al mostrar Datos " + e);
        }
    }
}
